namespace RtsDemo.Simulation;

public enum CombatEventKind : byte
{
    AttackStarted,
    ProjectileLaunched,
    ProjectileExpired,
    Impact,
    TargetDestroyed
}

public readonly record struct CombatEvent(
    long Tick,
    ulong Sequence,
    CombatEventKind Kind,
    int AttackerUnit,
    CombatTargetKind TargetKind,
    int TargetId,
    float Damage,
    float RemainingHealth,
    float DamagePerAttack,
    int AttacksApplied,
    bool BonusApplied,
    int ProjectileId);

public readonly record struct CombatEventBatch(
    CombatEvent[] Events,
    ulong LatestSequence,
    int LostEvents);

/// <summary>
/// Fixed-capacity derived event stream for presentation and diagnostics. Events are
/// regenerated by deterministic simulation and are intentionally not authoritative state.
/// </summary>
public sealed class CombatEventStream
{
    private readonly CombatEvent[] _events;
    private ulong _nextSequence = 1;
    private int _count;

    public CombatEventStream(int capacity = 4096)
    {
        if (capacity <= 0) throw new ArgumentOutOfRangeException(nameof(capacity));
        _events = new CombatEvent[capacity];
    }

    public int Capacity => _events.Length;
    public ulong LatestSequence => _nextSequence - 1;

    public void Publish(
        long tick,
        CombatEventKind kind,
        int attackerUnit,
        CombatTargetKind targetKind,
        int targetId,
        float damage = 0f,
        float remainingHealth = 0f,
        float damagePerAttack = 0f,
        int attacksApplied = 0,
        bool bonusApplied = false,
        int projectileId = -1)
    {
        var sequence = _nextSequence++;
        _events[(int)((sequence - 1) % (ulong)_events.Length)] = new CombatEvent(
            tick, sequence, kind, attackerUnit, targetKind, targetId,
            damage, remainingHealth, damagePerAttack, attacksApplied, bonusApplied,
            projectileId);
        if (_count < _events.Length) _count++;
    }

    public CombatEventBatch ReadAfter(ulong sequence)
    {
        var latest = LatestSequence;
        if (sequence >= latest) return new CombatEventBatch([], latest, 0);
        var oldest = _count == 0 ? latest + 1 : latest - (ulong)_count + 1;
        var requested = sequence + 1;
        var lostCount = requested < oldest ? oldest - requested : 0UL;
        var lost = (int)Math.Min(lostCount, int.MaxValue);
        var first = Math.Max(requested, oldest);
        var result = new CombatEvent[checked((int)(latest - first + 1))];
        for (var index = 0; index < result.Length; index++)
        {
            var eventSequence = first + (ulong)index;
            result[index] = _events[(int)((eventSequence - 1) % (ulong)_events.Length)];
        }
        return new CombatEventBatch(result, latest, lost);
    }

    public void Reset()
    {
        _nextSequence = 1;
        _count = 0;
        Array.Clear(_events);
    }
}
