namespace RtsDemo.Simulation;

public sealed class SimulationMetrics
{
    public long Tick { get; internal set; }
    public int MovingUnits { get; internal set; }
    public int ArrivedUnits { get; internal set; }
    public int WaitingForPathUnits { get; internal set; }
    public int PendingPathRequests { get; internal set; }
    public int PathsCompleted { get; internal set; }
    public int PathsFailed { get; internal set; }
    public int CollisionPairs { get; internal set; }
    public int CollisionBroadphasePairs { get; internal set; }
    public int CollisionMainIterations { get; internal set; }
    public int CollisionResidualPasses { get; internal set; }
    public int CollisionConstraintCalls { get; internal set; }
    public int CollisionResidualPairChecks { get; internal set; }
    public int CollisionResidualPairMoves { get; internal set; }
    public int CollisionVelocityProjections { get; internal set; }
    public int WorldVelocityProjections { get; internal set; }
    public float MaximumPenetration { get; internal set; }
    public int RepathRequests { get; internal set; }
    public int NavigationRevision { get; internal set; }
    public int NavigationInvalidations { get; internal set; }
    public int ClearanceBakeReloads { get; internal set; }
    public int RecoveryEvents { get; internal set; }
    public int UnreachableUnits { get; internal set; }
    public long GroupRoutePlans { get; internal set; }
    public long SharedRouteAssignments { get; internal set; }
    public long DestinationSlotSwaps { get; internal set; }
    public long DestinationLocalRematches { get; internal set; }
    public long DestinationLocalRematchedUnits { get; internal set; }
    public long DestinationOverflowAssignments { get; internal set; }
    public int MaximumDestinationStallTicks { get; internal set; }
    public int MaximumDestinationNearTicks { get; internal set; }
    public long DestinationYieldEvents { get; internal set; }
    public int ActiveDestinationYields { get; internal set; }
    public long PriorityPushPairs { get; internal set; }
    public float PriorityPushDisplacement { get; internal set; }
    public long DynamicBlockageSettles { get; internal set; }
    public int MaximumDynamicBlockageTicks { get; internal set; }
    public long ReservationMigrationAttempts { get; internal set; }
    public long ReservationMigrationFailures { get; internal set; }
    public int LastReservationMigrationUnits { get; internal set; }
    public float LastReservationMigrationClearance { get; internal set; }
    public int PendingUnitOrders { get; internal set; }
    public long CompletedQueuedOrders { get; internal set; }
    public int QueueOverflowEvents { get; internal set; }
    public long RepeatedAttackMoveUnitsCoalesced { get; internal set; }
    public double TotalMilliseconds { get; internal set; }
    public double EconomyMilliseconds { get; internal set; }
    public double ConstructionMilliseconds { get; internal set; }
    public int ConstructionCommitAttempts { get; internal set; }
    public int ConstructionCommitSuccesses { get; internal set; }
    public double ConstructionPlacementValidationMilliseconds { get; internal set; }
    public double ConstructionConnectivityBaselineMilliseconds { get; internal set; }
    public double ConstructionConnectivityCandidateMilliseconds { get; internal set; }
    public double ConstructionConnectivityCompareMilliseconds { get; internal set; }
    public long ConstructionConnectivityAllocatedBytes { get; internal set; }
    public int ConstructionConnectivityEvaluations { get; internal set; }
    public int ConstructionConnectivityBaselineRebuilds { get; internal set; }
    public double ConstructionOccupancyPlaceMilliseconds { get; internal set; }
    public double ConstructionRouteTopologyMilliseconds { get; internal set; }
    public double ConstructionPathInvalidationMilliseconds { get; internal set; }
    public double ProductionMilliseconds { get; internal set; }
    public double TechnologyMilliseconds { get; internal set; }
    public double EconomySystemMilliseconds { get; internal set; }
    public double LifecycleFinalizeMilliseconds { get; internal set; }
    public double CombatMilliseconds { get; internal set; }
    public long CombatAllocatedBytes { get; internal set; }
    public double CombatProjectileMilliseconds { get; internal set; }
    public double CombatUnitLoopMilliseconds { get; internal set; }
    public double CombatTargetSearchMilliseconds { get; internal set; }
    public int CombatTargetSearches { get; internal set; }
    public double PathMilliseconds { get; internal set; }
    public long PathAllocatedBytes { get; internal set; }
    public int PathFullConnectivityRebuilds { get; internal set; }
    public int PathIncrementalConnectivityUpdates { get; internal set; }
    public double PathConnectivityRefreshMilliseconds { get; internal set; }
    public double PathDirectCheckMilliseconds { get; internal set; }
    public double PathSearchMilliseconds { get; internal set; }
    public double PathSimplificationMilliseconds { get; internal set; }
    public double PathNormalizationMilliseconds { get; internal set; }
    public double PathStartEscapeMilliseconds { get; internal set; }
    public int PathExpandedNodes { get; internal set; }
    public int PathRawPoints { get; internal set; }
    public int PathSimplifiedPoints { get; internal set; }
    public int PathRequestsProcessed { get; internal set; }
    public int PathWorkUnits { get; internal set; }
    public int PathBudgetDeferrals { get; internal set; }
    public double PathSlowestRequestMilliseconds { get; internal set; }
    public int PathSlowestRequestUnit { get; internal set; } = -1;
    public int PathSlowestRequestCommandVersion { get; internal set; }
    public float PathSlowestRequestDistance { get; internal set; }
    public float PathSlowestRequestNavigationRadius { get; internal set; }
    public int PathSlowestRequestRouteWaypoints { get; internal set; }
    public int PathSlowestRequestExpandedNodes { get; internal set; }
    public int PathEdgeCacheInvalidatedStates { get; internal set; }
    public int PathEdgeCacheFullClears { get; internal set; }
    public int PathCompletedCacheHits { get; internal set; }
    public double PreferredVelocityMilliseconds { get; internal set; }
    public double ChokeMilliseconds { get; internal set; }
    public double SpatialHashMilliseconds { get; internal set; }
    public double SteeringMilliseconds { get; internal set; }
    public long SteeringAllocatedBytes { get; internal set; }
    public int SteeringNeighborPairs { get; internal set; }
    public int SteeringCandidateEvaluations { get; internal set; }
    public int SteeringMovingUnits { get; internal set; }
    public int SteeringPreferredFastPaths { get; internal set; }
    public int SteeringAvoidingUnits { get; internal set; }
    public int SteeringWorldSegmentProbes { get; internal set; }
    public int SteeringCollisionRiskNeighborChecks { get; internal set; }
    public int SteeringPredictedCollisionHits { get; internal set; }
    public int SteeringOverlappingNeighborHits { get; internal set; }
    public double IntegrateMilliseconds { get; internal set; }
    public double CollisionMilliseconds { get; internal set; }
    public long WorldConstraintCalls { get; internal set; }
    public long DynamicFootprintCandidateChecks { get; internal set; }
    public double RecoveryMilliseconds { get; internal set; }
    public double QueueMilliseconds { get; internal set; }
    public double VisibilityMilliseconds { get; internal set; }
    public double VisibilityDetectionMilliseconds { get; internal set; }
    public double VisibilityClearMilliseconds { get; internal set; }
    public double VisibilityUnitVisionMilliseconds { get; internal set; }
    public double VisibilityBuildingVisionMilliseconds { get; internal set; }
    public int VisibilityUnitCacheHits { get; internal set; }
    public int VisibilityUnitCacheRebuilds { get; internal set; }
    public int VisibilityCandidateCells { get; internal set; }
    public double MatchMilliseconds { get; internal set; }
    public double CommandMilliseconds { get; internal set; }
    public long QueueAllocatedBytes { get; internal set; }
    public long VisibilityAllocatedBytes { get; internal set; }
    public long MatchAllocatedBytes { get; internal set; }
    public long ConstructionAllocatedBytes { get; internal set; }
    public long ProductionAllocatedBytes { get; internal set; }
    public long TechnologyAllocatedBytes { get; internal set; }
    public long EconomySystemAllocatedBytes { get; internal set; }
    public long LifecycleFinalizeAllocatedBytes { get; internal set; }
    public long AllocatedBytes { get; internal set; }
}
