namespace RtsDemo.Simulation;

public sealed class SimulationMetrics
{
    public long Tick { get; internal set; }
    public int MovingUnits { get; internal set; }
    public int ArrivedUnits { get; internal set; }
    public int WaitingForPathUnits { get; internal set; }
    public int PendingPathRequests { get; internal set; }
    public int PathsCompleted { get; internal set; }
    public int PathsFailed { get; internal set; }
    public int CollisionPairs { get; internal set; }
    public float MaximumPenetration { get; internal set; }
    public int RepathRequests { get; internal set; }
    public int NavigationRevision { get; internal set; }
    public int NavigationInvalidations { get; internal set; }
    public int ClearanceBakeReloads { get; internal set; }
    public int RecoveryEvents { get; internal set; }
    public int UnreachableUnits { get; internal set; }
    public long GroupRoutePlans { get; internal set; }
    public long SharedRouteAssignments { get; internal set; }
    public long DestinationSlotSwaps { get; internal set; }
    public long DestinationLocalRematches { get; internal set; }
    public long DestinationLocalRematchedUnits { get; internal set; }
    public long DestinationOverflowAssignments { get; internal set; }
    public int MaximumDestinationStallTicks { get; internal set; }
    public int MaximumDestinationNearTicks { get; internal set; }
    public long DestinationYieldEvents { get; internal set; }
    public int ActiveDestinationYields { get; internal set; }
    public long PriorityPushPairs { get; internal set; }
    public float PriorityPushDisplacement { get; internal set; }
    public long DynamicBlockageSettles { get; internal set; }
    public int MaximumDynamicBlockageTicks { get; internal set; }
    public long ReservationMigrationAttempts { get; internal set; }
    public long ReservationMigrationFailures { get; internal set; }
    public int LastReservationMigrationUnits { get; internal set; }
    public float LastReservationMigrationClearance { get; internal set; }
    public int PendingUnitOrders { get; internal set; }
    public long CompletedQueuedOrders { get; internal set; }
    public int QueueOverflowEvents { get; internal set; }
    public double TotalMilliseconds { get; internal set; }
    public double EconomyMilliseconds { get; internal set; }
    public double ConstructionMilliseconds { get; internal set; }
    public double ProductionMilliseconds { get; internal set; }
    public double TechnologyMilliseconds { get; internal set; }
    public double EconomySystemMilliseconds { get; internal set; }
    public double LifecycleFinalizeMilliseconds { get; internal set; }
    public double CombatMilliseconds { get; internal set; }
    public double PathMilliseconds { get; internal set; }
    public int PathFullConnectivityRebuilds { get; internal set; }
    public int PathIncrementalConnectivityUpdates { get; internal set; }
    public double PathConnectivityRefreshMilliseconds { get; internal set; }
    public double PathDirectCheckMilliseconds { get; internal set; }
    public double PathSearchMilliseconds { get; internal set; }
    public double PathSimplificationMilliseconds { get; internal set; }
    public int PathExpandedNodes { get; internal set; }
    public int PathRawPoints { get; internal set; }
    public int PathSimplifiedPoints { get; internal set; }
    public double PreferredVelocityMilliseconds { get; internal set; }
    public double ChokeMilliseconds { get; internal set; }
    public double SpatialHashMilliseconds { get; internal set; }
    public double SteeringMilliseconds { get; internal set; }
    public double IntegrateMilliseconds { get; internal set; }
    public double CollisionMilliseconds { get; internal set; }
    public double RecoveryMilliseconds { get; internal set; }
    public double QueueMilliseconds { get; internal set; }
    public double VisibilityMilliseconds { get; internal set; }
    public double MatchMilliseconds { get; internal set; }
    public double CommandMilliseconds { get; internal set; }
    public long QueueAllocatedBytes { get; internal set; }
    public long VisibilityAllocatedBytes { get; internal set; }
    public long MatchAllocatedBytes { get; internal set; }
    public long ConstructionAllocatedBytes { get; internal set; }
    public long ProductionAllocatedBytes { get; internal set; }
    public long TechnologyAllocatedBytes { get; internal set; }
    public long EconomySystemAllocatedBytes { get; internal set; }
    public long LifecycleFinalizeAllocatedBytes { get; internal set; }
    public long AllocatedBytes { get; internal set; }
}
